{
  "testCase": [
    {
      "Id": "29",
      "ScenarioName": "Symbol Check",
      "Account": "RUAT_ACCOUNT_3",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "ROLX_Limit_NewAck",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 369,
      "Side": "2",
      "Symbol": "9999",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "30",
      "ScenarioName": "Price Limit Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price=Low-limit-1",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 58,
      "Side": "2",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "31",
      "ScenarioName": "Price Limit Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price=High-limit+1",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 119,
      "Side": "2",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "32",
      "ScenarioName": "Tick Size Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price<1,000 Tick size ≠ 1",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 371.5,
      "Side": "2",
      "Symbol": "4689",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "33",
      "ScenarioName": "Tick Size Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price<3,000 Tick side ≠ 1",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 2105.5,
      "Side": "2",
      "Symbol": "7203",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "34",
      "ScenarioName": "Tick Size Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price<10,000 Tick side ≠ 1",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 5000.5,
      "Side": "2",
      "Symbol": "9433",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "35",
      "ScenarioName": "Tick Size Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price<30,000 Tick side ≠ 5",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 26001,
      "Side": "2",
      "Symbol": "6954",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "36",
      "ScenarioName": "Tick Size Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price<100,000 Tick side ≠ 10",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 75001,
      "Side": "2",
      "Symbol": "9983",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "37",
      "ScenarioName": "Tick Size Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price<3,000 Tick side ≠ 1",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 2500.5,
      "Side": "2",
      "Symbol": "1721",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "38",
      "ScenarioName": "Tick Size Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price<5,000  Tick side ≠ 5",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 4000.5,
      "Side": "2",
      "Symbol": "2282",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "39",
      "ScenarioName": "Tick Size Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Price<30,000 Tick side ≠ 10",
      "OrderQty": 5,
      "OrdType": "2",
      "Price": 15001,
      "Side": "2",
      "Symbol": "1878",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "40",
      "ScenarioName": "Quantity Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Quantity=0 ",
      "OrderQty": 0,
      "OrdType": "1",
      "Side": "2",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "41",
      "ScenarioName": "Quantity Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Quantity=100(Round-lot) ",
      "OrderQty": 100,
      "OrdType": "1",
      "Side": "2",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "42",
      "ScenarioName": "Quantity Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Quantity=101(Mixed-lot) ",
      "OrderQty": 101,
      "OrdType": "1",
      "Side": "2",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "43",
      "ScenarioName": "Quantity Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Quantity=1(Lot size=1)",
      "OrderQty": 1,
      "OrdType": "1",
      "Side": "2",
      "Symbol": "8421",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "44",
      "ScenarioName": "Quantity Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Quantity=10(Lot size=10)",
      "OrderQty": 10,
      "OrdType": "1",
      "Side": "2",
      "Symbol": "1322",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "45",
      "ScenarioName": "Quantity Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Quantity=10(Lot size=10)",
      "OrderQty": 1000,
      "OrdType": "1",
      "Side": "2",
      "Symbol": "1773",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "46",
      "ScenarioName": "Order Type Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Order Type is not Limit/Market (Limit/Market Acceptable)",
      "OrderQty": 1,
      "OrdType": "9",
      "Side": "2",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "47",
      "ScenarioName": "TimeInForce Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "TimeInForce is not 0:Day",
      "OrderQty": 1,
      "OrdType": "1",
      "Side": "2",
      "Symbol": "1324",
      "TimeInForce": "6",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "48",
      "ScenarioName": "Order Side Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Order Side is not Buy/Sell (Buy/Sell Acceptable)",
      "OrderQty": 1,
      "OrdType": "1",
      "Side": "5",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "49",
      "ScenarioName": "Account Check",
      "Account": "RSIT_ACCOUNT_13",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Account is not the target test account",
      "OrderQty": 1,
      "OrdType": "1",
      "Side": "1",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "50",
      "ScenarioName": "Rule80A Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "Rule80A is not Agency/Principal",
      "OrderQty": 1,
      "OrdType": "1",
      "Side": "1",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "S",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    },
    {
      "Id": "51",
      "ScenarioName": "CashMargin Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "CashMargin is not Cash (Cash Acceptable)",
      "OrderQty": 1,
      "OrdType": "1",
      "Side": "1",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "2",
      "MarginTransactionType": "0"
    },
    {
      "Id": "52",
      "ScenarioName": "MarginTransactionType Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "MarginTransactionType is not 0-None",
      "OrderQty": 1,
      "OrdType": "1",
      "Side": "1",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROL",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "1"
    },
    {
      "Id": "53",
      "ScenarioName": "CrossingPriceType Check",
      "Account": "RUAT_ACCOUNT_2",
      "Market": "ROLX",
      "ActionType": "NewAck",
      "Comment": "CrossingPriceType is not ROL/REX",
      "OrderQty": 1,
      "OrdType": "1",
      "Side": "1",
      "Symbol": "1324",
      "TimeInForce": "0",
      "CrossingPriceType": "ROLX",
      "Rule80A": "P",
      "CashMargin": "1",
      "MarginTransactionType": "0"
    }
  ]
}
